### PR TITLE
policycoreutils: sepolicy: use dnf instead of yum

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1156547
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by mgrepl** [comment]
There is a traceback with this fix. You can see it using

$ sepolicy generate --init /usr/sbin/httpd

**Comment by ignatenkobrain** [comment]
@mgrepl can you show me traceback?

**Comment by mgrepl** [comment]
Sure.
http://fpaste.org/178297/

If you run

$ sepolicy generate --init /usr/sbin/httpd

you will get it.

**Comment by ignatenkobrain** [comment]
@mgrepl thanks for testing and providing reproducer. I tested and fixed tracebacks.

**Comment by ignatenkobrain** [comment]
@mgrepl I've generated policy with yum backend and with dnf backend. No differences in files.

**Comment by mgrepl** [comment]
It looks good. Thank you.

**Pull request merged**
